# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13d7QW8iduYcNKU1KkBa3CKPXu3vtxScr
"""

import streamlit as st
import pickle

# Load trained model
model = pickle.load(open("model.pkl", "rb"))

st.title("Car Dekho")

st.subheader("Enter Car Details")

# ---------------- NUMERICAL INPUTS ----------------

km_driven = st.number_input("Kilometers Driven", min_value=0)
seats = st.number_input("Seats", min_value=2, max_value=10)
yeard_old = st.number_input("Car Age (Years)", min_value=0)
mileage_value = st.number_input("Mileage (km/l)", min_value=0.0)
engine_value = st.number_input("Engine (CC)", min_value=0.0)
max_power_value = st.number_input("Max Power (bhp)", min_value=0.0)

# ---------------- CATEGORICAL INPUTS ----------------

# Fuel
fuel = st.selectbox(
    "Fuel Type",
    ["Petrol", "Diesel", "LPG", "CNG"]
)

# Seller Type
seller_type = st.selectbox(
    "Seller Type",
    ["Individual", "Dealer", "Trustmark Dealer"]
)

# Transmission
transmission = st.selectbox(
    "Transmission Type",
    ["Manual", "Automatic"]
)

# Owner (ORDINAL – ORDER IMPORTANT)
owner_order = [
    'Fourth & Above Owner',
    'Third Owner',
    'Second Owner',
    'First Owner',
    'Test Drive Car'
]

owner = st.selectbox(
    "Owner Type",
    owner_order
)

# ---------------- ENCODING (MUST MATCH TRAINING) ----------------

fuel_mapping = {
    "Petrol": 0,
    "Diesel": 1,
    "LPG": 2,
    "CNG": 3
}

seller_type_mapping = {
    "Individual": 0,
    "Dealer": 1,
    "Trustmark Dealer": 2
}

transmission_mapping = {
    "Manual": 1,
    "Automatic": 0
}

owner_mapping = {
    'Fourth & Above Owner': 0,
    'Third Owner': 1,
    'Second Owner': 2,
    'First Owner': 3,
    'Test Drive Car': 4
}

fuel_encoded = fuel_mapping[fuel]
seller_type_encoded = seller_type_mapping[seller_type]
transmission_encoded = transmission_mapping[transmission]
owner_encoded = owner_mapping[owner]

# ---------------- PREDICTION ----------------
if st.button("Predict Price"):
    prediction = model.predict(
    [[km_driven, owner_encoded, seats, yeard_old,
      mileage_value, engine_value, max_power_value,
      fuel_encoded, seller_type_encoded, transmission_encoded]]
)


    st.success(f"💰 Predicted Car Price: ₹{prediction[0]:,.2f}")
